### PR TITLE
Clean up code

### PR DESCRIPTION
**Pull request by johnletey**

### CODE REVIEW

**Comment by johnletey** [comment]
@nikitavoloboev How is this looking so far ... also, most vim themes have an option for italic comment, can I add this feature in this PR?

**Comment by nikitavoloboev** [comment]
What do you mean by italic comments? I don't have italic comments in my VSCode theme (Monokai Night) I believe.

**Comment by nikitavoloboev** [comment]
As for the PR, there is still some references to Ayu in there but I guess this a draft PR still so makes sense. But it does seem pretty good

**Comment by johnletey** [comment]
> there is still some references to Ayu in there

Yes ... I'm slowly getting rid of those ... should be ready to review soon

**Comment by johnletey** [comment]
> What do you mean by italic comments?

For instance, Nord has settings that you can change so that the actual comments are italicised



> I don't have italic comments in my VSCode theme (Monokai Night) I believe.

Yes ... the VSCode theme doesn't have anything, but I thought it would be a nice feature

**Comment by nikitavoloboev** [comment]
> but I thought it would be a nice feature

I think it can be a good choice although I want the theme be consistent with VSCode so lets see if @fabiospampinato wants to add italic comments to VS Code theme.

**Comment by johnletey** [comment]
Got it

**Comment by fabiospampinato** [comment]
I don't think I would like my comments in vscode italicized.

I would gladly add an option for this, but themes in vscode are defined in a very static way, it's not possible to implement this kind of option in a non-hacky (editing the extension at run-time and asking to reload the window) way.

**Comment by johnletey** [comment]
@fabiospampinato Totally fine ... was just an idea. Also, do you have any clean way of converting VSCode themes to ViM themes, because right now I just have your actual theme code open and I find matching values and input in color hex codes (not the best workflow)?

**Comment by fabiospampinato** [comment]
@johnletey no idea, I just barely know how to quit vim.

**Comment by johnletey** [comment]
> I just barely know how to quit vim.

Why does everyone think quitting vim is so hard!

**Comment by johnletey** [comment]
@nikitavoloboev This PR hasn't made any progress ... so I'm closing it. I'll definitely make sure to revisit later though!

**Pull request closed without merging**
