### PR TITLE
`ayu` -> `monokai-night`

### PR DESCRIPTION
**Pull request by johnletey**
I was getting an error:

shot 2019-02-20 at 11 27 00

This seems to fix it

### CODE REVIEW

**Comment by johnletey** [comment]
Note that I was setting my colorscheme with:

```vim
:silent! colorscheme monokai-night
```

and I wasn't anywhere setting my theme to ayu

**Comment by nikitavoloboev** [comment]
Sweet. 

The whole file needs to be redone actually #1 

But this is a good fix. Thanks

**Comment by johnletey** [comment]
I see

**Comment by johnletey** [comment]
@nikitavoloboev I've made some changes to nikitavoloboev/markdown-parser#16, if you want to take a look

**Pull request merged**
